# Linux DRM/KMS platform configuration.

set(RIDGEDASH_PLATFORM_USES_RAYLIB ON)
set(RIDGEDASH_PLATFORM_RAYLIB_NAME "DRM")
set(RIDGEDASH_PLATFORM_ENABLE_AUDIO ON)
set(RIDGEDASH_PLATFORM_COMPILE_DEFINITIONS
    RIDGEDASH_DRM_RENDER=1
    RIDGEDASH_USE_EVDEV_INPUT=1
    RIDGEDASH_ENABLE_AUDIO=1
)
set(RIDGEDASH_PLATFORM_LINK_LIBRARIES raylib)
