# Raw Linux framebuffer platform configuration.

set(RIDGEDASH_PLATFORM_USES_RAYLIB OFF)
set(RIDGEDASH_PLATFORM_ENABLE_AUDIO OFF)
set(RIDGEDASH_PLATFORM_COMPILE_DEFINITIONS
    RIDGEDASH_USE_FBDEV=1
    RIDGEDASH_USE_PLATFORM_COMPAT=1
    RIDGEDASH_SIMPLE_TEXT_RENDER=1
)
set(RIDGEDASH_PLATFORM_INCLUDE_DIRECTORIES
    "${RIDGEDASH_RAYLIB_DIR}/src/external"
)
